/**
 * Phase 7: Expense Management & Employee Reimbursements Audit Actions
 * Standardized audit action constants for immutable audit trail logging.
 */
export const ExpenseAuditAction = {
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_SUBMITTED: "EXPENSE_SUBMITTED",
  EXPENSE_APPROVED: "EXPENSE_APPROVED",
  EXPENSE_REJECTED: "EXPENSE_REJECTED",
  EXPENSE_POSTED: "EXPENSE_POSTED",
  EXPENSE_VOIDED: "EXPENSE_VOIDED",
  EXPENSE_PAID: "EXPENSE_PAID",
  EXPENSE_REIMBURSED: "EXPENSE_REIMBURSED",
  EXPENSE_ATTACHMENT_ADDED: "EXPENSE_ATTACHMENT_ADDED",
  EXPENSE_ATTACHMENT_REMOVED: "EXPENSE_ATTACHMENT_REMOVED",
  EXPENSE_CATEGORY_CREATED: "EXPENSE_CATEGORY_CREATED",
  EXPENSE_CATEGORY_UPDATED: "EXPENSE_CATEGORY_UPDATED",
  EXPENSE_CATEGORY_DEACTIVATED: "EXPENSE_CATEGORY_DEACTIVATED",
} as const;

export type ExpenseAuditActionType = (typeof ExpenseAuditAction)[keyof typeof ExpenseAuditAction];
